services:
  postgres:
    image: postgres
    container_name: postgres_ds
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: ${PG_DATA}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - doctor_suite
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak_ds
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - 9090:8080
    networks:
      - doctor_suite
    command:
      - "start-dev"
volumes:
  postgres:
    driver: local
networks:
  doctor_suite:
    driver: bridge
